In [1]:
import json
import csv
from pathlib import Path
from collections import Counter

import pandas as pd
from IPython.display import display

In [22]:
PROJECT_ROOT = Path.cwd().parents[1]

CSV_PATH = PROJECT_ROOT / "training" / "dataset" / "clinical_assertion" / "project-4-at-2026-10-14-08-05-5659dda1.csv"

OUTPUT_DIR = PROJECT_ROOT / "training" / "clinical_assertion" / "audit"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

assert CSV_PATH.exists(), f"Không tìm thấy file: {CSV_PATH}"

df = pd.read_csv(CSV_PATH, encoding="utf-8-sig")

print("Kích thước dữ liệu:", df.shape)
print("Các cột:", df.columns.tolist())

display(df.head(3))

Kích thước dữ liệu: (56, 10)
Các cột: ['Unnamed: 1', 'Unnamed: 2', 'annotation_id', 'annotator', 'created_at', 'id', 'label', 'lead_time', 'text', 'updated_at']

,Unnamed: 1,Unnamed: 2,annotation_id,annotator,created_at,id,label,lead_time,text,updated_at
0,NaN,NaN,20,1,2026-10-14T04:53:03.849146Z,1,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":13,""end"":17,""text"":""Răng"",""labels"":[""ORGAN""]},{""start"":18,""end"":22,""text"":""cháu"",""labels"":[""AGE""]},{""start"":45,""end"":48,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":111,""end"":119,""text"":""vài ngày"",""labels"":[""DATETIME""]},{""start"":158,""end"":161,""text"":""Chị"",""labels"":[""GENDER""]},{""start"":162,""end"":166,""text"":""cháu"",""labels"":[""AGE""]},{""start"":180,""end"":183,""text"":""chị"",""labels"":[""GENDER""]},{""start"":184,""end"":188,""text"":""cháu"",""labels"":[""AGE""]},{""start"":212,""end"":220,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":240,""end"":246,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":251,""end"":255,""text"":""cháu"",""labels"":[""AGE""]},{""start"":260,""end"":268,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":273,""end"":278,""text"":""có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":284,""end"":287,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":315,""end"":323,""text"":""chữa trị"",""labels"":[""TREATMENT""]},{""start"":35,""end"":38,""text"":""mủ "",""labels"":[""DISEASESYMTOM""]}]",49.356,"Chào bác sĩ,\nRăng cháu hiện tại có mủ ở dưới lợi nhưng khi đau cháu sẽ không ngủ được (quá đau). Tuy nhiên chỉ vài ngày là hết mà thỉnh thoảng nó lại bị đau. Chị cháu bảo là trước chị cháu cũng bị như vậy chỉ là đau răng tuổi dậy thì thôi. Bác sĩ cho cháu hỏi đau răng kèm có mủ dưới lợi là bệnh gì? Cháu có cần đi chữa trị không? Cháu cảm ơn.",2026-10-14T04:53:03.849158Z
1,NaN,NaN,19,1,2026-10-14T04:53:01.720650Z,2,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":36,""end"":46,""text"":""cuống lưỡi"",""labels"":[""DISEASESYMTOM""]},{""start"":132,""end"":136,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":163,""end"":173,""text"":""cuống lưỡi"",""labels"":[""ORGAN""]},{""start"":227,""end"":233,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":245,""end"":255,""text"":""cuống lưỡi"",""labels"":[""ORGAN""]},{""start"":309,""end"":313,""text"":""bệnh"",""labels"":[""DISEASESYMTOM""]},{""start"":334,""end"":345,""text"":""nhiệt miệng"",""labels"":[""DISEASESYMTOM""]},{""start"":369,""end"":376,""text"":""bác sĩ."",""labels"":[""OCCUPATION""]},{""start"":61,""end"":68,""text"":""nốt mụn"",""labels"":[""DISEASESYMTOM""]},{""start"":65,""end"":68,""text"":""mụn"",""labels"":[""DISEASESYMTOM""]}]",130.301,"Chào bác sĩ,\nEm thấy mặt dưới, phía cuống lưỡi của mình có 2 nốt mụn nhỏ, đỏ xung quanh, ở giữa có nhân trắng, đau nhẹ khi dùng đầu lưỡi chạm vào. Đồng thời, phía cuống lưỡi mặt trên cũng có các nốt lớn nổi lên, không gây đau. Bác sĩ cho em hỏi cuống lưỡi nổi mụn nhỏ là dấu hiệu bệnh gì? Có phải em đang mắc bệnh gì không hay chỉ bị nhiệt miệng bình thường? Em cảm ơn bác sĩ.",2026-10-14T04:53:01.720661Z
2,NaN,NaN,15,1,2026-10-14T04:51:06.131152Z,3,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":16,""end"":29,""text"":""tháng 4\/2020,"",""labels"":[""DATETIME""]},{""start"":55,""end"":66,""text"":""triệu chứng"",""labels"":[""DISEASESYMTOM""]},{""start"":67,""end"":84,""text"":""viêm amidan có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":110,""end"":119,""text"":""thời gian"",""labels"":[""DATETIME""]},{""start"":163,""end"":172,""text"":""1,2 tháng"",""labels"":[""DATETIME""]},{""start"":176,""end"":184,""text"":""01 lần),"",""labels"":[""DATETIME""]},{""start"":311,""end"":320,""text"":""rất nhiều"",""labels"":[""UNITCALIBRATOR""]},{""start"":361,""end"":367,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":379,""end"":396,""text"":""viêm amidan có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":401,""end"":404,""text"":""sốt"",""labels"":[""DISEASESYMTOM""]},{""start"":405,""end"":413,""text"":""tái phát"",""labels"":[""DISEASESYMTOM""]},{""start"":414,""end"":419,""text"":""nhiều"",""labels"":[""UNITCALIBRATOR""]},{""start"":455,""end"":462,""text"":""ung thư"",""labels"":[""DISEASESYMTOM""]},{""start"":463,""end"":471,""text"":""vòm họng"",""labels"":[""ORGAN""]},{""start"":204,""end"":207,""text"":""cảm"",""labels"":[""DISEASESYMTOM""]},{""start"":219,""end"":223,""text"":""viêm"",""labels"":[""DISEASESYMTOM""]},{""start"":250,""end"":254,""text"":""sốt "",""labels"":[""DISEASESYMTOM""]},{""start"":260,""end"":262,""text"":""mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":136,""end"":144,""text"":""tái phát"",""labels"":[""DISEASESYMTOM""]}]",157.141,"Chào bác sĩ,\nTừ tháng 4/2020, em mới xuất hiện lần đầu triệu chứng viêm amidan có mủ và sốt. Tuy nhiên, kể từ thời gian đó trở đi, bệnh tái phát nhiều lần (khoảng 1,2 tháng bị 01 lần), nhất là sau khi bị cảm tình trạng viêm nặng hơn lúc bình thường (sốt và có mủ, không tự khỏi được). Tình trạng trên ảnh hưởng rất nhiều đến sức khỏe và sinh hoạt của bản thân. Bác sĩ cho em hỏi viêm amidan có mủ kèm sốt tái phát nhiều lần phải làm sao? Em có nguy cơ bị ung thư vòm họng không? Em cảm ơn.",2026-10-14T04:51:06.131164Z

In [30]:
df = df.drop(columns=["Unnamed: 1","Unnamed: 2","annotation_id","annotator","created_at","lead_time","updated_at"])

In [31]:
display(
    df[["id", "label", "text"]].head(20)
)

,id,label,text
0,1,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":13,""end"":17,""text"":""Răng"",""labels"":[""ORGAN""]},{""start"":18,""end"":22,""text"":""cháu"",""labels"":[""AGE""]},{""start"":45,""end"":48,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":111,""end"":119,""text"":""vài ngày"",""labels"":[""DATETIME""]},{""start"":158,""end"":161,""text"":""Chị"",""labels"":[""GENDER""]},{""start"":162,""end"":166,""text"":""cháu"",""labels"":[""AGE""]},{""start"":180,""end"":183,""text"":""chị"",""labels"":[""GENDER""]},{""start"":184,""end"":188,""text"":""cháu"",""labels"":[""AGE""]},{""start"":212,""end"":220,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":240,""end"":246,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":251,""end"":255,""text"":""cháu"",""labels"":[""AGE""]},{""start"":260,""end"":268,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":273,""end"":278,""text"":""có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":284,""end"":287,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":315,""end"":323,""text"":""chữa trị"",""labels"":[""TREATMENT""]},{""start"":35,""end"":38,""text"":""mủ "",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nRăng cháu hiện tại có mủ ở dưới lợi nhưng khi đau cháu sẽ không ngủ được (quá đau). Tuy nhiên chỉ vài ngày là hết mà thỉnh thoảng nó lại bị đau. Chị cháu bảo là trước chị cháu cũng bị như vậy chỉ là đau răng tuổi dậy thì thôi. Bác sĩ cho cháu hỏi đau răng kèm có mủ dưới lợi là bệnh gì? Cháu có cần đi chữa trị không? Cháu cảm ơn."
1,2,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":36,""end"":46,""text"":""cuống lưỡi"",""labels"":[""DISEASESYMTOM""]},{""start"":132,""end"":136,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":163,""end"":173,""text"":""cuống lưỡi"",""labels"":[""ORGAN""]},{""start"":227,""end"":233,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":245,""end"":255,""text"":""cuống lưỡi"",""labels"":[""ORGAN""]},{""start"":309,""end"":313,""text"":""bệnh"",""labels"":[""DISEASESYMTOM""]},{""start"":334,""end"":345,""text"":""nhiệt miệng"",""labels"":[""DISEASESYMTOM""]},{""start"":369,""end"":376,""text"":""bác sĩ."",""labels"":[""OCCUPATION""]},{""start"":61,""end"":68,""text"":""nốt mụn"",""labels"":[""DISEASESYMTOM""]},{""start"":65,""end"":68,""text"":""mụn"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nEm thấy mặt dưới, phía cuống lưỡi của mình có 2 nốt mụn nhỏ, đỏ xung quanh, ở giữa có nhân trắng, đau nhẹ khi dùng đầu lưỡi chạm vào. Đồng thời, phía cuống lưỡi mặt trên cũng có các nốt lớn nổi lên, không gây đau. Bác sĩ cho em hỏi cuống lưỡi nổi mụn nhỏ là dấu hiệu bệnh gì? Có phải em đang mắc bệnh gì không hay chỉ bị nhiệt miệng bình thường? Em cảm ơn bác sĩ."
2,3,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":16,""end"":29,""text"":""tháng 4\/2020,"",""labels"":[""DATETIME""]},{""start"":55,""end"":66,""text"":""triệu chứng"",""labels"":[""DISEASESYMTOM""]},{""start"":67,""end"":84,""text"":""viêm amidan có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":110,""end"":119,""text"":""thời gian"",""labels"":[""DATETIME""]},{""start"":163,""end"":172,""text"":""1,2 tháng"",""labels"":[""DATETIME""]},{""start"":176,""end"":184,""text"":""01 lần),"",""labels"":[""DATETIME""]},{""start"":311,""end"":320,""text"":""rất nhiều"",""labels"":[""UNITCALIBRATOR""]},{""start"":361,""end"":367,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":379,""end"":396,""text"":""viêm amidan có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":401,""end"":404,""text"":""sốt"",""labels"":[""DISEASESYMTOM""]},{""start"":405,""end"":413,""text"":""tái phát"",""labels"":[""DISEASESYMTOM""]},{""start"":414,""end"":419,""text"":""nhiều"",""labels"":[""UNITCALIBRATOR""]},{""start"":455,""end"":462,""text"":""ung thư"",""labels"":[""DISEASESYMTOM""]},{""start"":463,""end"":471,""text"":""vòm họng"",""labels"":[""ORGAN""]},{""start"":204,""end"":207,""text"":""cảm"",""labels"":[""DISEASESYMTOM""]},{""start"":219,""end"":223,""text"":""viêm"",""labels"":[""DISEASESYMTOM""]},{""start"":250,""end"":254,""text"":""sốt "",""labels"":[""DISEASESYMTOM""]},{""start"":260,""end"":262,""text"":""mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":136,""end"":144,""text"":""tái phát"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nTừ tháng 4/2020, em mới xuất hiện lần đầu triệu chứng viêm amidan có mủ và sốt. Tuy nhiên, kể từ thời gian đó trở đi, bệnh tái phát nhiều lần (khoảng 1,2 tháng bị 01 lần), nhất là sau khi bị cảm tình trạng viêm nặng hơn lúc bình thường (sốt và có mủ, không tự khỏi được). Tình trạng trên ảnh hưởng rất nhiều đến sức khỏe và sinh hoạt của bản thân. Bác sĩ cho em hỏi viêm amidan có mủ kèm sốt tái phát nhiều lần phải làm sao? Em có nguy cơ bị ung thư vòm họng không? Em cảm ơn."
4,5,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":19,""end"":36,""text"":""tăng tiết mồ hôi,"",""labels"":[""DISEASESYMTOM""]},{""start"":45,""end"":53,""text"":""vùng mặt"",""labels"":[""ORGAN""]},{""start"":57,""end"":61,""text"":""ngực"",""labels"":[""ORGAN""]},{""start"":69,""end"":75,""text"":""nhiều."",""labels"":[""UNITCALIBRATOR""]},{""start"":76,""end"":82,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":94,""end"":110,""text"":""tăng tiết mồ hôi"",""labels"":[""DISEASESYMTOM""]},{""start"":113,""end"":121,""text"":""vùng mặt"",""labels"":[""ORGAN""]},{""start"":125,""end"":129,""text"":""ngực"",""labels"":[""ORGAN""]},{""start"":133,""end"":141,""text"":""điều trị"",""labels"":[""TREATMENT""]},{""start"":164,""end"":171,""text"":""bác sĩ."",""labels"":[""OCCUPATION""]}]","Chào bác sĩ,\nEm bị tăng tiết mồ hôi, nhất là vùng mặt và ngực ra rất nhiều. Bác sĩ cho em hỏi tăng tiết mồ hôi ở vùng mặt và ngực có điều trị được không? Em cảm ơn bác sĩ."
5,6,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":37,""end"":44,""text"":""ngủ dậy"",""labels"":[""DATETIME""]},{""start"":57,""end"":59,""text"":""ho"",""labels"":[""DISEASESYMTOM""]},{""start"":90,""end"":97,""text"":""khó thở"",""labels"":[""DISEASESYMTOM""]},{""start"":101,""end"":120,""text"":""tiếng thở khàn khàn"",""labels"":[""DISEASESYMTOM""]},{""start"":130,""end"":132,""text"":""ho"",""labels"":[""DISEASESYMTOM""]},{""start"":149,""end"":152,""text"":""cổ."",""labels"":[""ORGAN""]},{""start"":157,""end"":163,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":175,""end"":177,""text"":""ho"",""labels"":[""DISEASESYMTOM""]},{""start"":182,""end"":189,""text"":""ngủ dậy"",""labels"":[""DATETIME""]},{""start"":194,""end"":201,""text"":""khó thở"",""labels"":[""DISEASESYMTOM""]},{""start"":224,""end"":233,""text"":""buổi sáng"",""labels"":[""DATETIME""]},{""start"":248,""end"":255,""text"":""ngủ dậy"",""labels"":[""DATETIME""]},{""start"":256,""end"":265,""text"":""đánh răng"",""labels"":[""PERSONALCARE""]},{""start"":289,""end"":295,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":241,""end"":244,""text"":""bị "",""labels"":[""AFFIRMATION""]},{""start"":244,""end"":246,""text"":""ho"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nEm có biểu hiện sau khi ngủ dậy có cảm giác ho khi nhẹ khi nặng, có kèm theo khó thở mà tiếng thở khàn khàn cảm giác ho như có gì mắc ở cổ. Vậy bác sĩ cho em hỏi ho sau ngủ dậy kèm khó thở có sao không? Chỉ mỗi buổi sáng em mới bị ho, ngủ dậy đánh răng xong là hết. Em cảm ơn bác sĩ tư vấn."
6,7,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":19,""end"":22,""text"":""rát"",""labels"":[""DISEASESYMTOM""]},{""start"":23,""end"":27,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":32,""end"":40,""text"":""một tuần"",""labels"":[""DATETIME""]},{""start"":49,""end"":53,""text"":""khám"",""labels"":[""DIAGNOSTICS""]},{""start"":54,""end"":60,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":71,""end"":75,""text"":""viêm"",""labels"":[""DISEASESYMTOM""]},{""start"":76,""end"":80,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":87,""end"":97,""text"":""uống thuốc"",""labels"":[""TREATMENT""]},{""start"":98,""end"":110,""text"":""mấy ngày nay"",""labels"":[""DATETIME""]},{""start"":153,""end"":160,""text"":""bờ lưỡi"",""labels"":[""ORGAN""]},{""start"":170,""end"":180,""text"":""cuống lưỡi"",""labels"":[""ORGAN""]},{""start"":207,""end"":208,""text"":""u"",""labels"":[""DISEASESYMTOM""]},{""start"":227,""end"":230,""text"":""đau"",""labels"":[""DISEASESYMTOM""]},{""start"":244,""end"":251,""text"":""mấy hôm"",""labels"":[""DATETIME""]},{""start"":259,""end"":262,""text"":""đau"",""labels"":[""DISEASESYMTOM""]},{""start"":263,""end"":266,""text"":""hàm"",""labels"":[""ORGAN""]},{""start"":296,""end"":298,""text"":""ăn"",""labels"":[""FOODDRINK""]},{""start"":308,""end"":314,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":326,""end"":329,""text"":""rát"",""labels"":[""DISEASESYMTOM""]},{""start"":330,""end"":334,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":339,""end"":344,""text"":""nổi u"",""labels"":[""DISEASESYMTOM""]},{""start"":347,""end"":354,""text"":""bờ lưỡi"",""labels"":[""ORGAN""]},{""start"":363,""end"":375,""text"":""ung thư lưỡi"",""labels"":[""DISEASESYMTOM""]},{""start"":393,""end"":400,""text"":""bác sĩ."",""labels"":[""OCCUPATION""]},{""start"":148,""end"":153,""text"":""thấy "",""labels"":[""AFFIRMATION""]},{""start"":184,""end"":190,""text"":""nổi đỏ"",""labels"":[""DISEASESYMTOM""]},{""start"":20,""end"":21,""text"":""á"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nEm bị rát lưỡi hơn một tuần nay, đi khám bác sĩ bảo là bị viêm lưỡi nhưng uống thuốc mấy ngày nay cũng không thấy đỡ lắm. Em soi gương thấy bờ lưỡi trái gần cuống lưỡi có nổi đỏ lên như một cục u nhỏ. Em cũng thấy đau nhiều chỗ đó mấy hôm rồi và đau hàm trong bên trái khi nhai thức ăn nữa. Vậy bác sĩ cho em hỏi rát lưỡi kèm nổi u ở bờ lưỡi có phải ung thư lưỡi không? Em cảm ơn bác sĩ."
7,8,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":25,""end"":30,""text"":""1976."",""labels"":[""DATETIME""]},{""start"":38,""end"":44,""text"":""1 tuần"",""labels"":[""DATETIME""]},{""start"":60,""end"":68,""text"":""tai trái"",""labels"":[""ORGAN""]},{""start"":142,""end"":148,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":179,""end"":182,""text"":""tai"",""labels"":[""ORGAN""]},{""start"":214,""end"":221,""text"":""bác sĩ."",""labels"":[""OCCUPATION""]},{""start"":69,""end"":82,""text"":""kêu ro ro như"",""labels"":[""DISEASESYMTOM""]},{""start"":107,""end"":115,""text"":""khó chịu"",""labels"":[""DISEASESYMTOM""]},{""start"":56,""end"":59,""text"":""bên"",""labels"":[""LOCATION""]}]","Chào bác sĩ,\nEm sinh năm 1976. Khoảng 1 tuần nay, em bị bên tai trái kêu ro ro như có con gì bên trong rất khó chịu mà không có dịch chảy ra. Bác sĩ cho em hỏi có tiếng kêu trong tai là dấu hiệu bệnh gì? Em cảm ơn bác sĩ."
8,9,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":23,""end"":31,""text"":""viêm mũi"",""labels"":[""DISEASESYMTOM""]},{""start"":32,""end"":39,""text"":""dị ứng,"",""labels"":[""DISEASESYMTOM""]},{""start"":40,""end"":54,""text"":""chảy nước mũi,"",""labels"":[""DISEASESYMTOM""]},{""start"":64,""end"":70,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":82,""end"":90,""text"":""viêm mũi"",""labels"":[""DISEASESYMTOM""]},{""start"":91,""end"":97,""text"":""dị ứng"",""labels"":[""DISEASESYMTOM""]},{""start"":102,""end"":115,""text"":""chảy nước mũi"",""labels"":[""DISEASESYMTOM""]},{""start"":116,""end"":124,""text"":""điều trị"",""labels"":[""TREATMENT""]},{""start"":152,""end"":156,""text"":""xông"",""labels"":[""PERSONALCARE""]},{""start"":157,""end"":160,""text"":""mũi"",""labels"":[""ORGAN""]},{""start"":169,""end"":173,""text"":""nước"",""labels"":[""FOODDRINK""]},{""start"":174,""end"":178,""text"":""muối"",""labels"":[""DRUGCHEMICAL""]},{""start"":209,""end"":216,""text"":""bác sĩ."",""labels"":[""OCCUPATION""]},{""start"":55,""end"":62,""text"":""hắt hơi"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nEm hay bị viêm mũi dị ứng, chảy nước mũi, hắt hơi. Bác sĩ cho em hỏi viêm mũi dị ứng kèm chảy nước mũi điều trị thế nào? Em có thể xài máy xông mũi để xông nước muối sinh lý được không? Em cảm ơn bác sĩ."
9,10,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":34,""end"":39,""text"":""ngực,"",""labels"":[""ORGAN""]},{""start"":40,""end"":47,""text"":""hơi thở"",""labels"":[""DISEASESYMTOM""]},{""start"":80,""end"":87,""text"":""mệt mỏi"",""labels"":[""DISEASESYMTOM""]},{""start"":96,""end"":97,""text"":""2"",""labels"":[""ORGAN""]},{""start"":98,""end"":107,""text"":""cánh tay."",""labels"":[""ORGAN""]},{""start"":148,""end"":159,""text"":""triệu chứng"",""labels"":[""DISEASESYMTOM""]},{""start"":173,""end"":181,""text"":""ban đêm."",""labels"":[""DATETIME""]},{""start"":186,""end"":192,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":204,""end"":213,""text"":""nặng ngực"",""labels"":[""DISEASESYMTOM""]},{""start"":218,""end"":229,""text"":""hơi thở yếu"",""labels"":[""DISEASESYMTOM""]},{""start"":234,""end"":241,""text"":""ban đêm"",""labels"":[""DATETIME""]},{""start"":91,""end"":95,""text"":""lạnh"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nEm đột nhiên bị nặng ngực, hơi thở yếu hơn bình thường và kèm theo mệt mỏi và lạnh 2 cánh tay. Sau một lúc nghỉ ngơi, em mới đỡ lại và triệu chứng đó xuất hiện ban đêm. Vậy bác sĩ cho em hỏi nặng ngực kèm hơi thở yếu vào ban đêm có sao không? Em cảm ơn."
10,11,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":21,""end"":25,""text"":""cháu"",""labels"":[""AGE""]},{""start"":31,""end"":39,""text"":""4 tháng."",""labels"":[""DATETIME""]},{""start"":56,""end"":64,""text"":""mũi họng"",""labels"":[""ORGAN""]},{""start"":81,""end"":92,""text"":""kháng sinh,"",""labels"":[""DRUGCHEMICAL""]},{""start"":102,""end"":107,""text"":""thuốc"",""labels"":[""DRUGCHEMICAL""]},{""start"":108,""end"":116,""text"":""long đờm"",""labels"":[""DRUGCHEMICAL""]},{""start"":132,""end"":134,""text"":""ho"",""labels"":[""DISEASESYMTOM""]},{""start"":147,""end"":150,""text"":""mũi"",""labels"":[""ORGAN""]},{""start"":163,""end"":166,""text"":""đờm"",""labels"":[""DISEASESYMTOM""]},{""start"":185,""end"":191,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":203,""end"":211,""text"":""mũi họng"",""labels"":[""ORGAN""]},{""start"":215,""end"":218,""text"":""đờm"",""labels"":[""DISEASESYMTOM""]},{""start"":223,""end"":227,""text"":""sinh"",""labels"":[""DATETIME""]},{""start"":237,""end"":242,""text"":""thuốc"",""labels"":[""DRUGCHEMICAL""]},{""start"":264,""end"":272,""text"":""rửa mũi,"",""labels"":[""PERSONALCARE""]},{""start"":273,""end"":281,""text"":""xịt mũi,"",""labels"":[""PERSONALCARE""]},{""start"":282,""end"":296,""text"":""thuốc giảm ho,"",""labels"":[""DRUGCHEMICAL""]},{""start"":302,""end"":305,""text"":""đờm"",""labels"":[""DISEASESYMTOM""]},{""start"":326,""end"":332,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":333,""end"":335,""text"":""tư"",""labels"":[""PERSONALCARE""]},{""start"":68,""end"":71,""text"":""đờm"",""labels"":[""DISEASESYMTOM""]},{""start"":142,""end"":145,""text"":""đờm"",""labels"":[""DISEASESYMTOM""]},{""start"":139,""end"":142,""text"":""có "",""labels"":[""AFFIRMATION""]},{""start"":155,""end"":158,""text"":""có "",""labels"":[""AFFIRMATION""]},{""start"":212,""end"":215,""text"":""có "",""labels"":[""AFFIRMATION""]},{""start"":309,""end"":315,""text"":""không "",""labels"":[""NEGATION""]},{""start"":309,""end"":315,""text"":""không "",""labels"":[""NEGATION""]},{""start"":311,""end"":312,""text"":""ô"",""labels"":[""NEGATION""]},{""start"":315,""end"":319,""text"":""khỏi"",""labels"":[""DIAGNOSTICS""]}]","Chào bác sĩ,\nEm sinh cháu được 4 tháng. Hiện tại, em bị mũi họng có đờm, em uống kháng sinh, các kiểu thuốc long đờm mà không khỏi, ho vẫn có đờm, mũi vẫn có dịch đờm rất khó chịu. Vậy bác sĩ cho em hỏi mũi họng có đờm sau sinh nên dùng thuốc gì? Em vẫn dùng bình rửa mũi, xịt mũi, thuốc giảm ho, tiêu đờm mà không khỏi. Mong bác sĩ tư vấn, em cảm ơn."
11,12,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":13,""end"":24,""text"":""1 tuần nay,"",""labels"":[""DATETIME""]},{""start"":42,""end"":51,""text"":""khô họng,"",""labels"":[""DISEASESYMTOM""]},{""start"":52,""end"":59,""text"":""đau rát"",""labels"":[""DISEASESYMTOM""]},{""start"":62,""end"":66,""text"":""vùng"",""labels"":[""LOCATION""]},{""start"":67,""end"":71,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":96,""end"":99,""text"":""cộm"",""labels"":[""DISEASESYMTOM""]},{""start"":116,""end"":121,""text"":""thuốc"",""labels"":[""DRUGCHEMICAL""]},{""start"":122,""end"":132,""text"":""kháng sinh"",""labels"":[""DRUGCHEMICAL""]},{""start"":133,""end"":141,""text"":""mấy ngày"",""labels"":[""DATETIME""]},{""start"":168,""end"":174,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":186,""end"":195,""text"":""khô họng,"",""labels"":[""DISEASESYMTOM""]},{""start"":196,""end"":203,""text"":""đau rát"",""labels"":[""DISEASESYMTOM""]},{""start"":204,""end"":208,""text"":""vùng"",""labels"":[""ORGAN""]},{""start"":209,""end"":213,""text"":""lưỡi"",""labels"":[""ORGAN""]},{""start"":240,""end"":248,""text"":""điều trị"",""labels"":[""TREATMENT""]},{""start"":60,""end"":62,""text"":""ở "",""labels"":[""LOCATION""]},{""start"":96,""end"":103,""text"":""cộm cộm"",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\n1 tuần nay, em có hiện tượng khô họng, đau rát ở vùng lưỡi và khi nuốt có cảm giác cộm cộm. Em có dùng thuốc kháng sinh mấy ngày nay rồi mà không hết. Vậy bác sĩ cho em hỏi khô họng, đau rát vùng lưỡi là dấu hiệu bệnh gì? Cách điều trị thế nào? Em cảm ơn."
12,13,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":29,""end"":40,""text"":""viêm amidan"",""labels"":[""DISEASESYMTOM""]},{""start"":44,""end"":51,""text"":""men gan"",""labels"":[""DISEASESYMTOM""]},{""start"":52,""end"":56,""text"":""cao."",""labels"":[""UNITCALIBRATOR""]},{""start"":61,""end"":67,""text"":""bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":79,""end"":90,""text"":""viêm amidan"",""labels"":[""DISEASESYMTOM""]},{""start"":95,""end"":102,""text"":""men gan"",""labels"":[""DISEASESYMTOM""]},{""start"":103,""end"":106,""text"":""cao"",""labels"":[""UNITCALIBRATOR""]},{""start"":107,""end"":115,""text"":""điều trị"",""labels"":[""TREATMENT""]},{""start"":144,""end"":150,""text"":""amidan"",""labels"":[""ORGAN""]},{""start"":181,""end"":188,""text"":""men gan"",""labels"":[""DISEASESYMTOM""]},{""start"":189,""end"":192,""text"":""cao"",""labels"":[""UNITCALIBRATOR""]}]","Chào bác sĩ,\nHiện tại, em bị viêm amidan và men gan cao. Vậy bác sĩ cho em hỏi viêm amidan kèm men gan cao điều trị thế nào? Có phương pháp cắt amidan nào vẫn thực hiện được khi bị men gan cao không? Em cảm ơn."

In [13]:
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.width", None)

display(df[["id", "label", "text"]].head(1))

,id,label,text
0,1,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":13,""end"":17,""text"":""Răng"",""labels"":[""ORGAN""]},{""start"":18,""end"":22,""text"":""cháu"",""labels"":[""AGE""]},{""start"":45,""end"":48,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":111,""end"":119,""text"":""vài ngày"",""labels"":[""DATETIME""]},{""start"":158,""end"":161,""text"":""Chị"",""labels"":[""GENDER""]},{""start"":162,""end"":166,""text"":""cháu"",""labels"":[""AGE""]},{""start"":180,""end"":183,""text"":""chị"",""labels"":[""GENDER""]},{""start"":184,""end"":188,""text"":""cháu"",""labels"":[""AGE""]},{""start"":212,""end"":220,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":240,""end"":246,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":251,""end"":255,""text"":""cháu"",""labels"":[""AGE""]},{""start"":260,""end"":268,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":273,""end"":278,""text"":""có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":284,""end"":287,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":315,""end"":323,""text"":""chữa trị"",""labels"":[""TREATMENT""]},{""start"":35,""end"":38,""text"":""mủ "",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nRăng cháu hiện tại có mủ ở dưới lợi nhưng khi đau cháu sẽ không ngủ được (quá đau). Tuy nhiên chỉ vài ngày là hết mà thỉnh thoảng nó lại bị đau. Chị cháu bảo là trước chị cháu cũng bị như vậy chỉ là đau răng tuổi dậy thì thôi. Bác sĩ cho cháu hỏi đau răng kèm có mủ dưới lợi là bệnh gì? Cháu có cần đi chữa trị không? Cháu cảm ơn."

In [23]:
import json
import pandas as pd

records = []

for _, row in df.iterrows():
    raw_label = row["label"]

    if pd.isna(raw_label):
        continue

    spans = (
        json.loads(raw_label)
        if isinstance(raw_label, str)
        else raw_label
    )

    for span in spans:
        records.append({
            "id": row["id"],
            "start": span["start"],
            "end": span["end"],
            "text": span["text"],
            "label": ", ".join(span["labels"]),
        })

spans_df = pd.DataFrame(records)

display(spans_df)

     id  start  end             text           label
0     1      5   12          bác sĩ,      OCCUPATION
1     1     13   17             Răng           ORGAN
2     1     18   22             cháu             AGE
3     1     45   48              lợi           ORGAN
4     1    111  119         vài ngày        DATETIME
..   ..    ...  ...              ...             ...
944  64    186  197      cholesterol   DISEASESYMTOM
945  64    203  207             phần  UNITCALIBRATOR
946  64    208  212             thấp  UNITCALIBRATOR
947  64    238  245          bác sĩ.      OCCUPATION
948  64     67   82   bị thiếu lượng        DATETIME

[949 rows x 5 columns]

In [24]:

pd.set_option("display.max_colwidth", None)

label_counts = (
    spans_df["label"]
    .value_counts(dropna=False)
    .rename_axis("label")
    .reset_index(name="count")
)

label_counts["percentage"] = (
    label_counts["count"] / len(spans_df) * 100
).round(2)

display(label_counts)

             label  count  percentage
0    DISEASESYMTOM    365       38.46
1       OCCUPATION    141       14.86
2            ORGAN    124       13.07
3         DATETIME    101       10.64
4              AGE     49        5.16
5   UNITCALIBRATOR     32        3.37
6     DRUGCHEMICAL     28        2.95
7        FOODDRINK     25        2.63
8        TREATMENT     22        2.32
9     PERSONALCARE     21        2.21
10     DIAGNOSTICS     12        1.26
11     AFFIRMATION      7        0.74
12        LOCATION      7        0.74
13        NEGATION      7        0.74
14          GENDER      3        0.32
15      HISTORICAL      2        0.21
16         SURGERY      2        0.21
17   PREVENTIVEMED      1        0.11

In [26]:
import json
import pandas as pd

audit_records = []

for row_index, row in df.iterrows():
    raw_label = row.get("label")
    source_text = row.get("text")

    if pd.isna(raw_label) or pd.isna(source_text):
        continue

    try:
        spans = (
            json.loads(raw_label)
            if isinstance(raw_label, str)
            else raw_label
        )
    except (json.JSONDecodeError, TypeError):
        print(raw_label)
        audit_records.append({
            "row_index": row_index,
            "id": row.get("id"),
            "issue": "INVALID_JSON",
            "span_text": None,
            "details": "Không parse được cột label",
        })
        continue

    for span in spans:
        start = span.get("start")
        end = span.get("end")
        span_text = span.get("text", "")
        labels = span.get("labels", [])

        if not isinstance(start, int) or not isinstance(end, int):
            issue = "INVALID_OFFSET_TYPE"
            actual_text = None
        elif start < 0 or end > len(source_text) or start >= end:
            issue = "OFFSET_OUT_OF_RANGE"
            actual_text = None
        else:
            actual_text = source_text[start:end]
            issue = (
                None if actual_text == span_text
                else "TEXT_OFFSET_MISMATCH"
            )

        if issue:
            audit_records.append({
                "row_index": row_index,
                "id": row.get("id"),
                "issue": issue,
                "start": start,
                "end": end,
                "span_text": span_text,
                "actual_text": actual_text,
                "labels": labels,
                "details": "Kiểm tra thủ công trước khi sửa",
            })

audit_df = pd.DataFrame(audit_records)

print(f"Tổng số lỗi phát hiện: {len(audit_df)}")
display(audit_df)

Tổng số lỗi phát hiện: 3

,row_index,id,issue,start,end,span_text,actual_text,labels,details
0,3,4,TEXT_OFFSET_MISMATCH,69,74,giãn,ướng,[ORGAN],Kiểm tra thủ công trước khi sửa
1,48,49,TEXT_OFFSET_MISMATCH,185,191,mè đen,mè đen,[FOODDRINK],Kiểm tra thủ công trước khi sửa
2,48,49,TEXT_OFFSET_MISMATCH,193,195,mè,mè,[FOODDRINK],Kiểm tra thủ công trước khi sửa

In [33]:
df.head(1)

,id,label,text
0,1,"[{""start"":5,""end"":12,""text"":""bác sĩ,"",""labels"":[""OCCUPATION""]},{""start"":13,""end"":17,""text"":""Răng"",""labels"":[""ORGAN""]},{""start"":18,""end"":22,""text"":""cháu"",""labels"":[""AGE""]},{""start"":45,""end"":48,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":111,""end"":119,""text"":""vài ngày"",""labels"":[""DATETIME""]},{""start"":158,""end"":161,""text"":""Chị"",""labels"":[""GENDER""]},{""start"":162,""end"":166,""text"":""cháu"",""labels"":[""AGE""]},{""start"":180,""end"":183,""text"":""chị"",""labels"":[""GENDER""]},{""start"":184,""end"":188,""text"":""cháu"",""labels"":[""AGE""]},{""start"":212,""end"":220,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":240,""end"":246,""text"":""Bác sĩ"",""labels"":[""OCCUPATION""]},{""start"":251,""end"":255,""text"":""cháu"",""labels"":[""AGE""]},{""start"":260,""end"":268,""text"":""đau răng"",""labels"":[""DISEASESYMTOM""]},{""start"":273,""end"":278,""text"":""có mủ"",""labels"":[""DISEASESYMTOM""]},{""start"":284,""end"":287,""text"":""lợi"",""labels"":[""ORGAN""]},{""start"":315,""end"":323,""text"":""chữa trị"",""labels"":[""TREATMENT""]},{""start"":35,""end"":38,""text"":""mủ "",""labels"":[""DISEASESYMTOM""]}]","Chào bác sĩ,\nRăng cháu hiện tại có mủ ở dưới lợi nhưng khi đau cháu sẽ không ngủ được (quá đau). Tuy nhiên chỉ vài ngày là hết mà thỉnh thoảng nó lại bị đau. Chị cháu bảo là trước chị cháu cũng bị như vậy chỉ là đau răng tuổi dậy thì thôi. Bác sĩ cho cháu hỏi đau răng kèm có mủ dưới lợi là bệnh gì? Cháu có cần đi chữa trị không? Cháu cảm ơn."

In [34]:
import pandas as pd
from IPython.display import display

pd.set_option("display.max_colwidth", None)

label_counts = (
    spans_df["label"]
    .value_counts(dropna=False)
    .rename_axis("label")
    .reset_index(name="count")
)

label_counts["percentage"] = (
    label_counts["count"] / len(spans_df) * 100
).round(2)

display(label_counts)

             label  count  percentage
0    DISEASESYMTOM    365       38.46
1       OCCUPATION    141       14.86
2            ORGAN    124       13.07
3         DATETIME    101       10.64
4              AGE     49        5.16
5   UNITCALIBRATOR     32        3.37
6     DRUGCHEMICAL     28        2.95
7        FOODDRINK     25        2.63
8        TREATMENT     22        2.32
9     PERSONALCARE     21        2.21
10     DIAGNOSTICS     12        1.26
11     AFFIRMATION      7        0.74
12        LOCATION      7        0.74
13        NEGATION      7        0.74
14          GENDER      3        0.32
15      HISTORICAL      2        0.21
16         SURGERY      2        0.21
17   PREVENTIVEMED      1        0.11

In [35]:
import json
import pandas as pd

audit_records = []

for row_index, row in df.iterrows():
    raw_label = row.get("label")
    source_text = row.get("text")

    if pd.isna(raw_label) or pd.isna(source_text):
        continue

    try:
        spans = (
            json.loads(raw_label)
            if isinstance(raw_label, str)
            else raw_label
        )
    except (json.JSONDecodeError, TypeError):
        audit_records.append({
            "row_index": row_index,
            "id": row.get("id"),
            "issue": "INVALID_JSON",
            "span_text": None,
            "details": "Không parse được cột label",
        })
        continue

    for span in spans:
        start = span.get("start")
        end = span.get("end")
        span_text = span.get("text", "")
        labels = span.get("labels", [])

        if not isinstance(start, int) or not isinstance(end, int):
            issue = "INVALID_OFFSET_TYPE"
            actual_text = None
        elif start < 0 or end > len(source_text) or start >= end:
            issue = "OFFSET_OUT_OF_RANGE"
            actual_text = None
        else:
            actual_text = source_text[start:end]
            issue = (
                None if actual_text == span_text
                else "TEXT_OFFSET_MISMATCH"
            )

        if issue:
            audit_records.append({
                "row_index": row_index,
                "id": row.get("id"),
                "issue": issue,
                "start": start,
                "end": end,
                "span_text": span_text,
                "actual_text": actual_text,
                "labels": labels,
                "details": "Kiểm tra thủ công trước khi sửa",
            })

audit_df = pd.DataFrame(audit_records)

print(f"Tổng số lỗi phát hiện: {len(audit_df)}")
display(audit_df)

Tổng số lỗi phát hiện: 0

Empty DataFrame
Columns: []
Index: []

In [36]:
overlap_records = []

for row_index, row in df.iterrows():
    raw_label = row.get("label")
    source_text = row.get("text")

    if pd.isna(raw_label) or pd.isna(source_text):
        continue

    try:
        spans = (
            json.loads(raw_label)
            if isinstance(raw_label, str)
            else raw_label
        )
    except (json.JSONDecodeError, TypeError):
        continue

    spans = sorted(
        spans,
        key=lambda s: (s.get("start", -1), s.get("end", -1))
    )

    for i, first in enumerate(spans):
        for second in spans[i + 1:]:
            if second.get("start", -1) >= first.get("end", -1):
                break

            overlap_records.append({
                "row_index": row_index,
                "id": row.get("id"),
                "text": source_text,
                "span_1": first.get("text"),
                "label_1": first.get("labels"),
                "start_1": first.get("start"),
                "end_1": first.get("end"),
                "span_2": second.get("text"),
                "label_2": second.get("labels"),
                "start_2": second.get("start"),
                "end_2": second.get("end"),
            })

overlap_df = pd.DataFrame(overlap_records)

print(f"Tổng số cặp span chồng lấn: {len(overlap_df)}")
display(overlap_df)

Tổng số cặp span chồng lấn: 29

,row_index,id,text,span_1,label_1,start_1,end_1,span_2,label_2,start_2,end_2
0,1,2,"Chào bác sĩ,\nEm thấy mặt dưới, phía cuống lưỡi của mình có 2 nốt mụn nhỏ, đỏ xung quanh, ở giữa có nhân trắng, đau nhẹ khi dùng đầu lưỡi chạm vào. Đồng thời, phía cuống lưỡi mặt trên cũng có các nốt lớn nổi lên, không gây đau. Bác sĩ cho em hỏi cuống lưỡi nổi mụn nhỏ là dấu hiệu bệnh gì? Có phải em đang mắc bệnh gì không hay chỉ bị nhiệt miệng bình thường? Em cảm ơn bác sĩ.",nốt mụn,[DISEASESYMTOM],61,68,mụn,[DISEASESYMTOM],65,68
1,6,7,"Chào bác sĩ,\nEm bị rát lưỡi hơn một tuần nay, đi khám bác sĩ bảo là bị viêm lưỡi nhưng uống thuốc mấy ngày nay cũng không thấy đỡ lắm. Em soi gương thấy bờ lưỡi trái gần cuống lưỡi có nổi đỏ lên như một cục u nhỏ. Em cũng thấy đau nhiều chỗ đó mấy hôm rồi và đau hàm trong bên trái khi nhai thức ăn nữa. Vậy bác sĩ cho em hỏi rát lưỡi kèm nổi u ở bờ lưỡi có phải ung thư lưỡi không? Em cảm ơn bác sĩ.",rát,[DISEASESYMTOM],19,22,á,[DISEASESYMTOM],20,21
2,10,11,"Chào bác sĩ,\nEm sinh cháu được 4 tháng. Hiện tại, em bị mũi họng có đờm, em uống kháng sinh, các kiểu thuốc long đờm mà không khỏi, ho vẫn có đờm, mũi vẫn có dịch đờm rất khó chịu. Vậy bác sĩ cho em hỏi mũi họng có đờm sau sinh nên dùng thuốc gì? Em vẫn dùng bình rửa mũi, xịt mũi, thuốc giảm ho, tiêu đờm mà không khỏi. Mong bác sĩ tư vấn, em cảm ơn.",không,[NEGATION],309,315,không,[NEGATION],309,315
3,10,11,"Chào bác sĩ,\nEm sinh cháu được 4 tháng. Hiện tại, em bị mũi họng có đờm, em uống kháng sinh, các kiểu thuốc long đờm mà không khỏi, ho vẫn có đờm, mũi vẫn có dịch đờm rất khó chịu. Vậy bác sĩ cho em hỏi mũi họng có đờm sau sinh nên dùng thuốc gì? Em vẫn dùng bình rửa mũi, xịt mũi, thuốc giảm ho, tiêu đờm mà không khỏi. Mong bác sĩ tư vấn, em cảm ơn.",không,[NEGATION],309,315,ô,[NEGATION],311,312
4,10,11,"Chào bác sĩ,\nEm sinh cháu được 4 tháng. Hiện tại, em bị mũi họng có đờm, em uống kháng sinh, các kiểu thuốc long đờm mà không khỏi, ho vẫn có đờm, mũi vẫn có dịch đờm rất khó chịu. Vậy bác sĩ cho em hỏi mũi họng có đờm sau sinh nên dùng thuốc gì? Em vẫn dùng bình rửa mũi, xịt mũi, thuốc giảm ho, tiêu đờm mà không khỏi. Mong bác sĩ tư vấn, em cảm ơn.",không,[NEGATION],309,315,ô,[NEGATION],311,312
...,...,...,...,...,...,...,...,...,...,...,...
24,45,46,"Chào bác sĩ,\nTôi có xạ trị xong 30 tia. Bây giờ đã được hơn 1 tháng, nhưng hiện tại cổ họng tôi nuốt bị đau. Vậy bác sĩ cho tôi hỏi nuốt đau sau xạ trị ung thư có sao không? Nguyên nhân do đâu? Tôi cảm ơn.",nuốt đau,[DISEASESYMTOM],132,140,đau,[DISEASESYMTOM],137,140
25,45,46,"Chào bác sĩ,\nTôi có xạ trị xong 30 tia. Bây giờ đã được hơn 1 tháng, nhưng hiện tại cổ họng tôi nuốt bị đau. Vậy bác sĩ cho tôi hỏi nuốt đau sau xạ trị ung thư có sao không? Nguyên nhân do đâu? Tôi cảm ơn.",nuốt đau,[DISEASESYMTOM],132,140,đau,[DISEASESYMTOM],137,140
26,45,46,"Chào bác sĩ,\nTôi có xạ trị xong 30 tia. Bây giờ đã được hơn 1 tháng, nhưng hiện tại cổ họng tôi nuốt bị đau. Vậy bác sĩ cho tôi hỏi nuốt đau sau xạ trị ung thư có sao không? Nguyên nhân do đâu? Tôi cảm ơn.",ung thư,[DISEASESYMTOM],152,159,n,[DISEASESYMTOM],153,154
27,49,50,"Chào bác sĩ,\nEm bị sốt cách đây 1 tuần mà vẫn chưa khỏi. Hiện giờ, em chỉ còn sốt nhẹ nhưng đau đầu, chóng mặt rất nhiều, không ăn được gì, ăn vào là nôn, không thể tỉnh táo, người lúc nào cũng nóng. Bác sĩ cho em hỏi sốt, chóng mặt kèm nôn có sao không? Em cảm ơn bác sĩ.",sốt,[DISEASESYMTOM],218,221,ố,[DISEASESYMTOM],219,220
28,51,52,"Chào bác sĩ,\nEm bị tiểu nhiều, cứ tiểu xong lại buồn tiểu luôn. Ngày có 24 giờ lúc nào em cũng trong tình trạng buồn tiểu. Ngày em có khi làm nhiều lúc quên đi nhưng buổi tối rất khó chịu, lúc nào cũng muốn tiểu. Em có khám ở bệnh viện thì bác sĩ bảo em bị bàng quang tăng hoạt. Vậy bác sĩ cho em hỏi có thể chữa khỏi hoàn toàn bàng quang tăng hoạt không? Nếu có thuốc thì phải uống bao lâu? Em cảm ơn.",tăng hoạt,[DISEASESYMTOM],268,277,hoạt.,[DISEASESYMTOM],273,278

In [37]:
from pathlib import Path

OUTPUT_DIR = Path.cwd() / "training" / "clinical_assertion" / "audit"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

label_counts.to_csv(
    OUTPUT_DIR / "label_counts.csv",
    index=False,
    encoding="utf-8-sig",
)

audit_df.to_csv(
    OUTPUT_DIR / "audit_issues.csv",
    index=False,
    encoding="utf-8-sig",
)

overlap_df.to_csv(
    OUTPUT_DIR / "overlapping_spans.csv",
    index=False,
    encoding="utf-8-sig",
)

print(f"Đã lưu báo cáo tại: {OUTPUT_DIR.resolve()}")

Đã lưu báo cáo tại: D:\project\clinic_management_system_ai\training\notebooks\training\clinical_assertion\audit