In [10]:
import pandas as pd
df = pd.read_csv("./../dataset/test/test_data.csv")
df = df.rename(columns={'Patient_comment': 'text', 'Patient_Category': 'label'}) 
df = df[["label", "text"]]
df

,label,text,text_vi
0,Cơ xương khớp,I have muscle pain in my left leg,Tôi bị đau cơ ở chân trái.
1,Chấn thương chỉnh hình,I have cut my finger because of playing footba...,Tôi bị đứt tay khi chơi bóng đá và phải bôi ke...
2,Da liễu,I have acne in my face and other problems in m...,Tôi bị mụn trứng cá trên mặt và các vấn đề khá...
3,Cơ xương khớp,I have a strange rash on my arm,Tôi bị phát ban lạ trên cánh tay.
4,Tiêu hóa,I have a sharp pain in my lower stomach.,Tôi bị đau nhói ở vùng bụng dưới.
...,...,...,...
199,Thần kinh,I feel dizzy whenever I stand up.,Tôi cảm thấy chóng mặt mỗi khi đứng dậy.
200,Cơ xương khớp,"Annoyance starts suddenly, often after an inju...","Cảm giác khó chịu xuất hiện đột ngột, thường l..."
201,Nhãn khoa,I feel pain in my eyes I can see fog,"Tôi cảm thấy đau nhức mắt, tôi nhìn thấy như c..."
202,Thần kinh,Can't keep focus,Không thể tập trung
203,Hô hấp,I feel fluid trying to come up when I cough.,Tôi cảm thấy có chất lỏng muốn trào ra khi ho.

In [7]:
df["label"].value_counts()

label
Cơ xương khớp             70
Da liễu                   24
Thần kinh                 21
Nội khoa                  18
Ngoại khoa                15
Hô hấp                    11
Nhãn khoa                 10
Tim mạch                   9
Tai Mũi Họng               8
Tâm thần                   7
Tiêu hóa                   6
Chấn thương chỉnh hình     5
Name: count, dtype: int64

In [4]:
symptom_to_department = {
    "Knee pain": "Cơ xương khớp",
    "Feeling dizzy": "Thần kinh",
    "Joint pain": "Cơ xương khớp",
    "Back pain": "Cơ xương khớp",
    "Blurry vision": "Nhãn khoa",
    "Muscle pain": "Cơ xương khớp",
    "Infected wound": "Ngoại khoa",
    "Foot ache": "Cơ xương khớp",
    "Heart hurts": "Tim mạch",
    "Acne": "Da liễu",
    "Skin issue": "Da liễu",
    "Head ache": "Thần kinh",
    "Body feels weak": "Nội khoa",
    "Internal pain": "Nội khoa",
    "Ear ache": "Tai Mũi Họng",
    "Shoulder pain": "Cơ xương khớp",
    "Hair falling out": "Da liễu",
    "Neck pain": "Cơ xương khớp",
    "Emotional pain": "Tâm thần",
    "Stomach ache": "Tiêu hóa",
    "Cough": "Hô hấp",
    "Injury from sports": "Chấn thương chỉnh hình",
    "Hard to breath": "Hô hấp",
    "Open wound": "Ngoại khoa",
    "Feeling cold": "Nội khoa",
}

df["label"] = df["label"].replace(symptom_to_department)

In [6]:
df.to_csv("D:/project/clinic_management_system_ai/training/dataset/test/test_data.csv", index=False)

In [13]:
import pandas as pd
df = pd.read_csv("./../dataset/test/test_data.csv")
df["text"] = df["text_vi"]
df = df.drop(columns=["text_vi"])
df.head(10)

                    label                                               text
0           Cơ xương khớp                         Tôi bị đau cơ ở chân trái.
1  Chấn thương chỉnh hình  Tôi bị đứt tay khi chơi bóng đá và phải bôi ke...
2                 Da liễu  Tôi bị mụn trứng cá trên mặt và các vấn đề khá...
3           Cơ xương khớp                  Tôi bị phát ban lạ trên cánh tay.
4                Tiêu hóa                  Tôi bị đau nhói ở vùng bụng dưới.
5           Cơ xương khớp                Tôi bị đau đầu gối khi đi bộ nhiều.
6                Tim mạch  Bác sĩ ơi, tôi cảm thấy một cơn đau dữ dội và ...
7           Cơ xương khớp                                          Đừng khóc
8                Tim mạch                                Tôi có thuốc trị ho
9                  Hô hấp  Trước đây, tôi thường thở hổn hển sau khi leo ...

In [16]:
df_data1 = pd.read_csv("./../dataset/training/patientComments01.csv")
df_data2 = pd.read_csv("./../dataset/training/patientComments02.csv")
df = pd.concat([df_data1, df_data2], ignore_index=True)
df["label"].value_counts()

label
Da liễu                 1054
Chỉnh hình               882
Tai Mũi Họng             826
Thấp khớp                735
Tiêu hóa                 659
Ngoại khoa               564
Đa khoa                  524
Hô hấp                   383
Nhãn khoa                346
Tim mạch                 323
Thấp khớp/Tiêu hóa       320
Thần kinh/Tiêu hóa       263
Thấp khớp/Chỉnh hình     251
Tâm thần                 231
Truyền nhiễm             150
Cơ xương khớp            100
Dị ứng - Miễn dịch       100
Thần kinh                 50
Tiết niệu                 50
Nội tiết                  50
Name: count, dtype: int64

In [ ]:
label_mapping = {
    "Thấp khớp/Tiêu hóa": "Cơ xương khớp",
    "Thấp khớp": "Cơ xương khớp",
    "Chỉnh hình": "Chấn thương chỉnh hình",
}

df["label"] = df["label"].replace(label_mapping)

In [23]:
df["label"].value_counts()

label
Cơ xương khớp             1155
Da liễu                   1054
Chấn thương chỉnh hình     882
Tai Mũi Họng               826
Tiêu hóa                   659
Ngoại khoa                 564
Đa khoa                    524
Hô hấp                     383
Nhãn khoa                  346
Tim mạch                   323
Thần kinh/Tiêu hóa         263
Thấp khớp/Chỉnh hình       251
Tâm thần                   231
Truyền nhiễm               150
Dị ứng - Miễn dịch         100
Thần kinh                   50
Tiết niệu                   50
Nội tiết                    50
Name: count, dtype: int64

In [24]:
df.to_csv("./../dataset/training/symptomDisease.csv", index=False)

In [35]:
df["label"].value_counts()

label
Cơ xương khớp             1406
Da liễu                   1054
Chấn thương chỉnh hình     882
Tai Mũi Họng               826
Tiêu hóa                   659
Ngoại khoa                 564
Đa khoa                    524
Hô hấp                     383
Nhãn khoa                  346
Tim mạch                   323
Thần kinh                  313
Tâm thần                   231
Truyền nhiễm               150
Dị ứng - Miễn dịch         100
Tiết niệu                   50
Nội tiết                    50
Name: count, dtype: int64

In [34]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
df.loc[df["label"] == "Thấp khớp/Chỉnh hình","label"] = "Cơ xương khớp"

In [36]:
df.to_csv("D:\\project\\clinic_management_system_ai\\training\\dataset\\training_data.csv", index=False)

In [ ]:
df = pd.read_csv("./../dataset/test/test_data.csv")
df["label"].value_counts()

label
Cơ xương khớp             70
Da liễu                   24
Thần kinh                 21
Nội khoa                  18
Ngoại khoa                15
Hô hấp                    11
Nhãn khoa                 10
Tim mạch                   9
Tai Mũi Họng               8
Tâm thần                   7
Tiêu hóa                   6
Chấn thương chỉnh hình     5
Name: count, dtype: int64

In [56]:
df = pd.read_csv("./../dataset/training/training_data.csv")
df["label"].value_counts()

label
Cơ xương khớp             1406
Da liễu                   1054
Chấn thương chỉnh hình     882
Tai Mũi Họng               826
Tiêu hóa                   659
Ngoại khoa                 564
Đa khoa                    524
Hô hấp                     383
Nhãn khoa                  346
Tim mạch                   323
Thần kinh                  313
Tâm thần                   231
Truyền nhiễm               150
Dị ứng - Miễn dịch         100
Tiết niệu                   50
Nội tiết                    50
Name: count, dtype: int64

In [43]:
duplicates = df[df.duplicated("text", keep=False)]

print("Số dòng duplicate:", len(duplicates))

print(
    duplicates
    .sort_values("text")
    .to_string(index=False)
)

Số dòng duplicate: 6756
                 label                                                                                                                                                                                                        text
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
          Tai Mũi Họng                                                                                                                        Ban đầu chỉ là chứng ù tai, nhưng giờ cơn đau nhức nhối và không thể chịu đựng được.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
                Hô hấp                                                                                                                                                                                   Buổi sáng tôi thở rất to.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
              Tiêu hóa                                                                                                                                                                            Bên trái của tôi đau nhức nhiều.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
            Ngoại khoa                                                                                           Bạn sẽ không tin đâu, nhưng vết thương nhiễm trùng trên tay tôi là do một vết cắt giấy mà tôi đã không coi trọng.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
         Cơ xương khớp                                                                                                                                                     Bắp chân tôi có cảm giác như bị căng cứng và nhức nhối.
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                 Bệnh mãn tính của nang tóc và tuyến bã nhờn
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
               Da liễu                                                                                                                                                                Bệnh mãn tính của nang tóc và tuyến bã nhờn.
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
Chấn thương chỉnh hình                                                                                                                                                  Bệnh xương mãn tính ở mức độ gấp đôi của Estremidades dưới
          Tai Mũi Họng                                                                                                                                                                                      Bị cảm lạnh và ho nặng
          Tai Mũi Họng                                                                                                                                                                                      Bị cảm lạnh và ho nặng
          Tai Mũi Họng                                                                                                                                                                                      Bị cảm lạnh và ho nặng

In [44]:
print("TOTAL:", len(df))

print(
    "DUPLICATE TEXT:",
    df.duplicated(subset=["text"]).sum()
)

print(
    "DUPLICATE TEXT + LABEL:",
    df.duplicated(subset=["text", "label"]).sum()
)

print(
    "UNIQUE TEXT:",
    df["text"].nunique()
)

print(
    "UNIQUE TEXT + LABEL:",
    df[["text", "label"]].drop_duplicates().shape[0]
)

TOTAL: 7861
DUPLICATE TEXT: 6025
DUPLICATE TEXT + LABEL: 6019
UNIQUE TEXT: 1836
UNIQUE TEXT + LABEL: 1842

In [46]:
for text, group in conflict_df.groupby("text"):
    print("=" * 100)
    print("TEXT:", text)

    for label in group["label"].unique():
        print("  -", label)

====================================================================================================
TEXT: Mỗi khi mang vác đồ nặng, tôi cảm thấy như lưng mình sắp gãy.
  - Da liễu
  - Chấn thương chỉnh hình
====================================================================================================
TEXT: Tôi bị phát ban lạ trên cánh tay.
  - Da liễu
  - Cơ xương khớp
====================================================================================================
TEXT: Tôi bị rụng tóc rất nhiều.
  - Đa khoa
  - Da liễu
====================================================================================================
TEXT: Tôi cảm thấy tức ngực.
  - Hô hấp
  - Tai Mũi Họng
====================================================================================================
TEXT: Vết thương bị nhiễm trùng của tôi gây ra sốt.
  - Ngoại khoa
  - Da liễu
====================================================================================================
TEXT: Đầu tôi đau quá.
  - Cơ xương khớp
  - Thần kinh

In [47]:
df_clean = df.drop_duplicates(
    subset=["text", "label"]
).copy()

print("Before:", len(df))
print("After:", len(df_clean))

Before: 7861
After: 1842

In [52]:
df_clean = df_clean[
    ~df_clean["text"].isin(["Tôi bị phát ban lạ trên cánh tay."])
].copy()

In [54]:
df_clean = df.drop_duplicates(
    subset=["text", "label"]
).copy()

print(df_clean["label"].value_counts())
print()
print("TOTAL UNIQUE:", len(df_clean))
print("UNIQUE TEXT:", df_clean["text"].nunique())

label
Da liễu                   287
Cơ xương khớp             234
Tiêu hóa                  181
Hô hấp                    170
Truyền nhiễm              143
Nhãn khoa                 126
Dị ứng - Miễn dịch        100
Ngoại khoa                 97
Chấn thương chỉnh hình     90
Tai Mũi Họng               86
Tim mạch                   80
Thần kinh                  72
Đa khoa                    52
Tiết niệu                  50
Nội tiết                   50
Tâm thần                   24
Name: count, dtype: int64

TOTAL UNIQUE: 1842
UNIQUE TEXT: 1836

In [48]:
df_clean.to_csv("D:\\project\\clinic_management_system_ai\\training\\dataset\\training_data_clean.csv", index=False)

In [57]:
conflict = (
    df.groupby("text")["label"]
      .nunique()
)

conflict_texts = conflict[conflict > 1].index

for text, group in df[df["text"].isin(conflict_texts)].groupby("text"):
    print("=" * 100)
    print("TEXT:", text)
    print(group[["label", "text"]].drop_duplicates().to_string(index=False))

====================================================================================================
TEXT: Mỗi khi mang vác đồ nặng, tôi cảm thấy như lưng mình sắp gãy.
                 label                                                          text
               Da liễu Mỗi khi mang vác đồ nặng, tôi cảm thấy như lưng mình sắp gãy.
Chấn thương chỉnh hình Mỗi khi mang vác đồ nặng, tôi cảm thấy như lưng mình sắp gãy.
====================================================================================================
TEXT: Tôi bị phát ban lạ trên cánh tay.
        label                              text
Cơ xương khớp Tôi bị phát ban lạ trên cánh tay.
      Da liễu Tôi bị phát ban lạ trên cánh tay.
====================================================================================================
TEXT: Tôi bị rụng tóc rất nhiều.
  label                       text
Đa khoa Tôi bị rụng tóc rất nhiều.
Da liễu Tôi bị rụng tóc rất nhiều.
====================================================================================================
TEXT: Tôi cảm thấy tức ngực.
       label                   text
      Hô hấp Tôi cảm thấy tức ngực.
Tai Mũi Họng Tôi cảm thấy tức ngực.
====================================================================================================
TEXT: Vết thương bị nhiễm trùng của tôi gây ra sốt.
     label                                          text
   Da liễu Vết thương bị nhiễm trùng của tôi gây ra sốt.
Ngoại khoa Vết thương bị nhiễm trùng của tôi gây ra sốt.
====================================================================================================
TEXT: Đầu tôi đau quá.
        label             text
    Thần kinh Đầu tôi đau quá.
Cơ xương khớp Đầu tôi đau quá.

In [58]:
df_clean["word_count"] = (
    df_clean["text"]
    .astype(str)
    .str.split()
    .str.len()
)

print(
    df_clean
    .sort_values("word_count")
    [["label", "text", "word_count"]]
    .head(100)
    .to_string(index=False)
)

                 label                         text  word_count
Chấn thương chỉnh hình                    Đừng khóc           2
               Da liễu                 tóc tôi rụng           3
              Tâm thần                Tôi thất vọng           3
             Nhãn khoa           Tôi không nhìn rõ.           4
             Thần kinh              Tôi bị đau đầu.           4
         Cơ xương khớp             Vai tôi đau quá.           4
          Tai Mũi Họng            Tôi cảm thấy lạnh           4
         Cơ xương khớp             Tôi bị đau chân.           4
              Tâm thần            Tôi cảm thấy buồn           4
Chấn thương chỉnh hình            Lưng tôi đau quá.           4
               Da liễu             Tôi bị thiếu tóc           4
              Tim mạch           Lòng tôi đau nhói.           4
             Thần kinh             Đầu tôi đau quá.           4
             Nhãn khoa              Tôi bị nhìn mờ.           4
         Cơ xương khớp            Chân tôi đau quá.           4
          Tai Mũi Họng             Tôi bị khô họng.           4
             Nhãn khoa            Máy khử trùng mắt           4
              Tiêu hóa              Tôi bị khó tiêu           4
         Cơ xương khớp              Vai tôi bị đau.           4
            Ngoại khoa           Nhiễm trùng vết mổ           4
               Đa khoa             Tôi cảm thấy yếu           4
          Tai Mũi Họng                Tai tôi bị ù.           4
Chấn thương chỉnh hình             Tôi bị đau khớp.           4
               Da liễu              Da tôi bị ngứa.           4
          Tai Mũi Họng               Tôi bị sổ mũi.           4
         Cơ xương khớp               Tôi bị đau cơ.           4
          Tai Mũi Họng               Đau tai dữ dội           4
          Tai Mũi Họng             Tôi bị ngứa tai.           4
          Tai Mũi Họng             Tai tôi đau quá.           4
         Cơ xương khớp             Đầu tôi đau quá.           4
             Thần kinh          Không thể tập trung           4
              Tiêu hóa             Tôi bị đau bụng.           4
              Tiêu hóa            Đau ruột mãn tính           4
               Da liễu         đỏ mặt kèm theo ngứa           5
          Tai Mũi Họng       Tôi cảm thấy tức ngực.           5
         Cơ xương khớp       Tôi không thể xoay cổ.           5
          Tai Mũi Họng       Tôi không thể ngừng ho           5
               Đa khoa     Tôi cảm thấy choáng váng           5
             Thần kinh         Tôi cảm thấy đau đầu           5
               Da liễu            Tôi có làn da khô           5
               Da liễu         Mặt tôi nổi đầy mụn.           5
          Tai Mũi Họng          Tôi bị ho khan nặng           5
         Cơ xương khớp         Tôi bị đau cơ thang.           5
              Tiêu hóa          Đau nhói và khó thở           5
               Da liễu      Tóc tôi rụng rất nhiều.           5
               Da liễu         Trên mặt tôi có mụn.           5
          Tai Mũi Họng      Tôi không thể ngừng ho.           5
              Tâm thần         Tôi bị bệnh tâm thần           5
            Ngoại khoa        Vết thương vẫn còn hở           5
                Hô hấp       Tôi cảm thấy tức ngực.           5
               Da liễu         Tôi bị mụn khắp mặt.           5
               Da liễu         sử dụng thuốc bổ tóc           5
            Ngoại khoa      Có một người bị thương.           5
          Tai Mũi Họng     Toàn thân tôi lạnh cóng.           5
Chấn thương chỉnh hình         Đầu gối tôi đau quá.           5
          Tai Mũi Họng           Tôi bị ho rất nặng           5
              Tiêu hóa       Tôi cảm thấy đau bụng.           5
          Tai Mũi Họng       Tôi không thể thở được           5
              Tiêu hóa       Tôi cảm thấy buồn nôn.           5
         Cơ xương khớp          Vai tôi đau dữ dội.           5
               Da liễu           Tôi bị mụn ở lưng.           5
         Cơ xương khớp            Đau ở vùng cổ lớn           5
              Tim mạch          Tôi có thuốc trị ho           5
          Tai Mũi Họng       Tôi cảm thấy đau họng.           5
Chấn thương chỉnh hình       Tôi cảm thấy đau lưng.           5
              Tiêu hóa         Tôi bị đau nội tạng.           5
              Tâm thần     Tôi bị rối loạn cảm xúc.           6
               Da liễu     Tôi bị phát ban trên da.           6
              Tiêu hóa    Đau bụng sau khi uống sữa           6
             Thần kinh        Sọ bị vỡ như quả hạch           6
                Hô hấp    Buổi sáng tôi thở rất to.           6
              Tiêu hóa đau quặn bụng khắp vùng bụng           6
Chấn thương chỉnh hình   Tôi bị đau lưng rất nhiều.           6
         Cơ xương khớp     Tôi cảm thấy đau ở chân.           6
               Da liễu  Tóc tôi không được đẹp lắm.           6
              Tim mạch    Trái tim đau nhói vô cùng           6
         Cơ xương khớp       Tôi bị đau vai dữ dội.           6
               Da liễu      Tôi cần gãi da mỗi phút           6
          Tai Mũi Họng       Tôi bị đau nhói ở tai.           6
          Tai Mũi Họng     Tôi không thở được vì ho           6
         Cơ xương khớp      Tôi bị nhức nhối ở vai.           6
         Cơ xương khớp       Tôi cảm thấy đau ở cổ.           6
               Da liễu         Tôi có vấn đề về da.           6
                Hô hấp    Ngực tôi đau khi hít thở.           6
               Đa khoa   Tôi bị rụng tóc rất nhiều.           6
             Nhãn khoa       Tôi có đôi mắt mờ đục.           6
               Da liễu Một cơn rụng tóc khủng khiếp           6
         Cơ xương khớp        Tôi bị đau nhói ở cổ.           6
Chấn thương chỉnh hình      Tôi bị đau khi gập tay.           6
              Tâm thần     Tôi cảm thấy muốn tự tử.           6
          Tai Mũi Họng     Tôi không ngủ được vì ho           6
         Cơ xương khớp     Cổ tôi cảm thấy cứng đờ.           6
              Tâm thần  Tôi luôn cảm thấy rất buồn.           6
          Tai Mũi Họng       Bị cảm lạnh và ho nặng           6
               Da liễu   Tôi bị rụng tóc rất nhiều.           6
              Tiêu hóa      Tôi bị đau nhói ở bụng.           6
              Tim mạch    Tim tôi như muốn nổ tung.           6
                Hô hấp      Khi đi bộ, tôi khó thở.           6
               Da liễu      Da tôi bị ngứa và viêm.           6
              Tiêu hóa     Tôi bị đau đầu mỗi ngày.           6

In [59]:
df_clean["word_count"] = (
    df_clean["text"]
    .astype(str)
    .str.split()
    .str.len()
)

print(
    df_clean
    .sort_values("word_count")
    [["label", "text", "word_count"]]
    .head(100)
    .to_string(index=False)
)

                 label                         text  word_count
Chấn thương chỉnh hình                    Đừng khóc           2
               Da liễu                 tóc tôi rụng           3
              Tâm thần                Tôi thất vọng           3
             Nhãn khoa           Tôi không nhìn rõ.           4
             Thần kinh              Tôi bị đau đầu.           4
         Cơ xương khớp             Vai tôi đau quá.           4
          Tai Mũi Họng            Tôi cảm thấy lạnh           4
         Cơ xương khớp             Tôi bị đau chân.           4
              Tâm thần            Tôi cảm thấy buồn           4
Chấn thương chỉnh hình            Lưng tôi đau quá.           4
               Da liễu             Tôi bị thiếu tóc           4
              Tim mạch           Lòng tôi đau nhói.           4
             Thần kinh             Đầu tôi đau quá.           4
             Nhãn khoa              Tôi bị nhìn mờ.           4
         Cơ xương khớp            Chân tôi đau quá.           4
          Tai Mũi Họng             Tôi bị khô họng.           4
             Nhãn khoa            Máy khử trùng mắt           4
              Tiêu hóa              Tôi bị khó tiêu           4
         Cơ xương khớp              Vai tôi bị đau.           4
            Ngoại khoa           Nhiễm trùng vết mổ           4
               Đa khoa             Tôi cảm thấy yếu           4
          Tai Mũi Họng                Tai tôi bị ù.           4
Chấn thương chỉnh hình             Tôi bị đau khớp.           4
               Da liễu              Da tôi bị ngứa.           4
          Tai Mũi Họng               Tôi bị sổ mũi.           4
         Cơ xương khớp               Tôi bị đau cơ.           4
          Tai Mũi Họng               Đau tai dữ dội           4
          Tai Mũi Họng             Tôi bị ngứa tai.           4
          Tai Mũi Họng             Tai tôi đau quá.           4
         Cơ xương khớp             Đầu tôi đau quá.           4
             Thần kinh          Không thể tập trung           4
              Tiêu hóa             Tôi bị đau bụng.           4
              Tiêu hóa            Đau ruột mãn tính           4
               Da liễu         đỏ mặt kèm theo ngứa           5
          Tai Mũi Họng       Tôi cảm thấy tức ngực.           5
         Cơ xương khớp       Tôi không thể xoay cổ.           5
          Tai Mũi Họng       Tôi không thể ngừng ho           5
               Đa khoa     Tôi cảm thấy choáng váng           5
             Thần kinh         Tôi cảm thấy đau đầu           5
               Da liễu            Tôi có làn da khô           5
               Da liễu         Mặt tôi nổi đầy mụn.           5
          Tai Mũi Họng          Tôi bị ho khan nặng           5
         Cơ xương khớp         Tôi bị đau cơ thang.           5
              Tiêu hóa          Đau nhói và khó thở           5
               Da liễu      Tóc tôi rụng rất nhiều.           5
               Da liễu         Trên mặt tôi có mụn.           5
          Tai Mũi Họng      Tôi không thể ngừng ho.           5
              Tâm thần         Tôi bị bệnh tâm thần           5
            Ngoại khoa        Vết thương vẫn còn hở           5
                Hô hấp       Tôi cảm thấy tức ngực.           5
               Da liễu         Tôi bị mụn khắp mặt.           5
               Da liễu         sử dụng thuốc bổ tóc           5
            Ngoại khoa      Có một người bị thương.           5
          Tai Mũi Họng     Toàn thân tôi lạnh cóng.           5
Chấn thương chỉnh hình         Đầu gối tôi đau quá.           5
          Tai Mũi Họng           Tôi bị ho rất nặng           5
              Tiêu hóa       Tôi cảm thấy đau bụng.           5
          Tai Mũi Họng       Tôi không thể thở được           5
              Tiêu hóa       Tôi cảm thấy buồn nôn.           5
         Cơ xương khớp          Vai tôi đau dữ dội.           5
               Da liễu           Tôi bị mụn ở lưng.           5
         Cơ xương khớp            Đau ở vùng cổ lớn           5
              Tim mạch          Tôi có thuốc trị ho           5
          Tai Mũi Họng       Tôi cảm thấy đau họng.           5
Chấn thương chỉnh hình       Tôi cảm thấy đau lưng.           5
              Tiêu hóa         Tôi bị đau nội tạng.           5
              Tâm thần     Tôi bị rối loạn cảm xúc.           6
               Da liễu     Tôi bị phát ban trên da.           6
              Tiêu hóa    Đau bụng sau khi uống sữa           6
             Thần kinh        Sọ bị vỡ như quả hạch           6
                Hô hấp    Buổi sáng tôi thở rất to.           6
              Tiêu hóa đau quặn bụng khắp vùng bụng           6
Chấn thương chỉnh hình   Tôi bị đau lưng rất nhiều.           6
         Cơ xương khớp     Tôi cảm thấy đau ở chân.           6
               Da liễu  Tóc tôi không được đẹp lắm.           6
              Tim mạch    Trái tim đau nhói vô cùng           6
         Cơ xương khớp       Tôi bị đau vai dữ dội.           6
               Da liễu      Tôi cần gãi da mỗi phút           6
          Tai Mũi Họng       Tôi bị đau nhói ở tai.           6
          Tai Mũi Họng     Tôi không thở được vì ho           6
         Cơ xương khớp      Tôi bị nhức nhối ở vai.           6
         Cơ xương khớp       Tôi cảm thấy đau ở cổ.           6
               Da liễu         Tôi có vấn đề về da.           6
                Hô hấp    Ngực tôi đau khi hít thở.           6
               Đa khoa   Tôi bị rụng tóc rất nhiều.           6
             Nhãn khoa       Tôi có đôi mắt mờ đục.           6
               Da liễu Một cơn rụng tóc khủng khiếp           6
         Cơ xương khớp        Tôi bị đau nhói ở cổ.           6
Chấn thương chỉnh hình      Tôi bị đau khi gập tay.           6
              Tâm thần     Tôi cảm thấy muốn tự tử.           6
          Tai Mũi Họng     Tôi không ngủ được vì ho           6
         Cơ xương khớp     Cổ tôi cảm thấy cứng đờ.           6
              Tâm thần  Tôi luôn cảm thấy rất buồn.           6
          Tai Mũi Họng       Bị cảm lạnh và ho nặng           6
               Da liễu   Tôi bị rụng tóc rất nhiều.           6
              Tiêu hóa      Tôi bị đau nhói ở bụng.           6
              Tim mạch    Tim tôi như muốn nổ tung.           6
                Hô hấp      Khi đi bộ, tôi khó thở.           6
               Da liễu      Da tôi bị ngứa và viêm.           6
              Tiêu hóa     Tôi bị đau đầu mỗi ngày.           6